Yet another strange fix for Windows only
Windows claims to support POSIX, and claims to support AI_ADDRCONFIG,
(https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo)

But I get compile errors:
```
src/resolve.c:610:21: error: 'AI_ADDRCONFIG' undeclared (first use in this function); did you mean 'LUP_ADDRCONFIG'?
```

Probably because of the compatibility straight jacket that Windows seems
to insist on applying to any improvements.